### ISSUE TITLE
Consider making local storage optional

### ISSUE THREAD

**Issue by gregorskii** [deamme/laco#1]
Looks great, and a simple api. Looking over the source I see it sets the stores in the local storage. Would it be wise (if stores get large) to make local storage optional?

I think it would make sense for each store to have a config that determines if it pushes to local storage.

Cheers!

**Comment by deamme** [comment]
@gregorskii This is actually old code from when I supported state persistence through DevTools. I was not aware of this, sorry about that. (this was only a development feature)
