### ISSUE TITLE
QUESTION: does it works with react native?

### ISSUE THREAD

**Issue by badpenguin** [deamme/laco#4]
I'm using React Native.
I've upgraded to react 16.7.0 but i get: 
undefined is not a function (evaluating react_1.useState(store.get()) ...)
i'm just using the simple CounterStore example with useStore()

Do i need react 16.8beta?

I got it working using the "subscribe" but i wish to try useStore too.

**Comment by deamme** [comment]
You should be able to use it with `16.8.0-alpha.1` - you can install it by doing `npm i react@next`

**Comment by badpenguin** [comment]
Nope those not work with Reac Native at the moment, i need to wait for a new version of React Native that works with hooks. Its working great with Subscribe anyway :)

**Comment by deamme** [comment]
@badpenguin Ah, alright :)!
